### ISSUE TITLE
Missing `pre-commit-config.yaml`

### ISSUE THREAD

**Issue by jvpichowski** [pathpy/pathpyG#185]
I use the devcontainer.

When committing it says:
```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

In the documentation for `Contributing.md` it says:

```
The checks are documented in detail in `pre-commit-config.yaml`.  
```

I can't find that file, too. Also running `pre-commit install` did not help.

Did I miss-configure something?

**Comment by M-Lampert** [comment]
I removed the precommit configurations in #188 since they were more annoying than helping. DevContainers and potentially also other setups where `precommit install` was executed during setup need to run `precommit uninstall` as a fix. Rebuilding the dev container would also work. Afterwards this should hopefully never lead to any problems since it should be completely removed now.
